---
source: tooling/nargo_cli/tests/execute.rs
expression: "&format!(\"success: {:?}\\nexit_code: {}\\n----- stdout -----\\n{}\\n----- stderr -----\\n{}\",\noutput.status.success(), output.status.code().unwrap_or(!0), stdout, stderr)"
---
success: false
exit_code: 1
----- stdout -----

----- stderr -----
warning: unused variable removed_slice
   ┌─ src/main.nr:10:10
   │
10 │     let (removed_slice, removed_elem) = slice.remove(10);
   │          ------------- unused variable
   │

warning: unused variable removed_elem
   ┌─ src/main.nr:10:25
   │
10 │     let (removed_slice, removed_elem) = slice.remove(10);
   │                         ------------ unused variable
   │

error: No method named 'push_back' found for type '[Field; 2]'
  ┌─ src/main.nr:4:17
  │
4 │         slice = slice.push_back(y);
  │                 ------------------
  │

error: No method named 'push_back' found for type '[Field; 2]'
  ┌─ src/main.nr:5:17
  │
5 │         slice = slice.push_back(x);
  │                 ------------------
  │

error: No method named 'push_back' found for type '[Field; 2]'
  ┌─ src/main.nr:7:17
  │
7 │         slice = slice.push_back(x);
  │                 ------------------
  │

error: No method named 'remove' found for type '[Field; 2]'
   ┌─ src/main.nr:10:41
   │
10 │     let (removed_slice, removed_elem) = slice.remove(10);
   │                                         ----------------
   │

error: Cannot assign an expression of type (_, _) to a value of type _
   ┌─ src/main.nr:10:9
   │
10 │     let (removed_slice, removed_elem) = slice.remove(10);
   │         -----------------------------
   │

Aborting due to 5 previous errors
